project:
  type: website

website:
  title: "micpram.github.io"
  navbar:
   right:
   - text: "Home"
     file: index.qmd
   - text: "About"
     file: about.qmd
   - text: "Example Analysis"
     file: example.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

