project:
  type: website
  render:
    - "*.qmd"
    - "!posts/2022-12-13-flexdashboard/*.Rmd"
    
website:
  title: "Michael Ramirez"
  description: "test test"
  navbar:
    right:
      - text: "Home"
        file: README.md
        menu:
        - text: "About Me"
          href: ABOUT.md
        - text: "Data Analysis"
          href: Analysis.md
format:
  html:
    theme: simplex
    toc: true
    css: styles.css
    code-overflow: wrap

editor: source

execute:
  freeze: auto
