---
title: ABOUT ME
layout: template
filename: ABOUT.md
--- 

## Education
BA in Psychology & Physiology, Cal Poly Pomona
MPH in Sociocultural Diversity & Health, University of California--Irvine
PhD in Mental Health, Johns Hopkins Bloomberg School of Public Health

## Current Projects
1. Machine learning to predict overdose among people who inject drugs in Baltimore, MD
2. Identifying temporal predictors of subsequent overdose among people who inject drugs in Baltimore, MD
3. Understanding exposure to fentanyl and determining risk differences among people who inject drugs in Baltimore, MD

Overall, my projects at the moment center around substance use disorder and focus on the population of people who inject drugs in Baltimore, MD. Usually, when I relocate to a new area, I enjoy getting involved in local health and social equity issues. Prior to coming to Baltimore, I was focused on environmental toxins and linking lead exposure to lower cognitive performance among children and Alzheimer's among older adults in SoCal. 

## Personal Interests 
Aside from school and work, I enjoy running and playing volleyball. I just finished my second marathon at the Baltimore Running Festival and also play intermediate volleyball across Baltimore under the VOLO league.
